// src/components/RecipeImage.tsx
import * as React from "react";
import { GatsbyImage, IGatsbyImageData } from "gatsby-plugin-image";
import { Box, Tooltip, Typography } from "@mui/material";
import InfoOutlined from "@mui/icons-material/InfoOutlined";

interface RecipeImageProps {
  imageData?: IGatsbyImageData;
  title?: string;
  maxWidth?: number;           // optional; default 720
  showTooltip?: boolean;       // optional; default true
}

const RecipeImage: React.FC<RecipeImageProps> = ({
  imageData,
  title,
  maxWidth = 720,
  showTooltip = true,
}) => {
  if (!imageData) return null;

  return (
    <>
      <Box sx={{ display: "flex", justifyContent: "center", px: { xs: 2, md: 8 }, mt: 2, mb: 1 }}>
        <Box sx={{ width: "100%", maxWidth, borderRadius: 2, overflow: "hidden", boxShadow: 3 }}>
          <GatsbyImage
            image={imageData}
            alt={title || "Recipe image"}
            // Let Gatsby control the intrinsic ratio (no cropping):
            style={{ width: "100%", height: "auto", display: "block" }}
            // Keep default objectFit (cover) OFF by not setting imgStyle
          />
        </Box>
      </Box>

      {showTooltip && (
        <Box sx={{ display: "flex", justifyContent: "center", mb: 3 }}>
          <Tooltip title="This recipe image may have been generated by generative AI." arrow>
            <Typography
              variant="caption"
              sx={{ color: "text.secondary", display: "inline-flex", alignItems: "center", gap: 0.5, cursor: "help" }}
            >
              <InfoOutlined fontSize="inherit" />
              Image info
            </Typography>
          </Tooltip>
        </Box>
      )}
    </>
  );
};

export default RecipeImage;
